version: "3.9"

services:
  db:
    image: postgres
    container_name: todo_db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  django:
    build: ./
    working_dir: /code
    container_name: django
    command: bash -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: choco.settings

  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    ports:
      - '15672:15672'

  celery:
    command: celery -A choco worker -B -l info
    working_dir: /code
    build: .
    volumes:
      - .:/code
    depends_on:
      - rabbitmq
      - django
    restart: on-failure
    environment:
      - DJANGO_SETTINGS_MODULE=choco.settings